service: BGG-api-json

frameworkVersion: ">=1.2.0 <2.0.0"

provider:
  name: aws
  runtime: python3.6
  region: us-east-1
  logRetentionInDays: 1

functions:
  boardgames:
    handler: handler.boardgames
    events:
      - http:
          path: boardgames/{id}/
          method: get

  boardgameexpansions:
    handler: handler.boardgameexpansions
    events:
      - http:
          path: boardgameexpansions/{id}/
          method: get
plugins:
  - serverless-python-requirements
  - serverless-domain-manager


custom:
  customDomain:
    domainName: bgg.boardgamelibrary.xyz
    basePath: ''
    stage: ${self:provider.stage}
    createRoute53Record: true
